apiVersion: v1
kind: ServiceAccount
metadata:
  name: cval-evaluator
  labels:
    app.kubernetes.io/name: cval-evaluator
    app.kubernetes.io/component: health-evaluator
automountServiceAccountToken: false
